### PR TITLE
v3

### LINKED ISSUE #1108: v3 ⛱️
### Package Scope

etc

### Description

milestone

### Possible Solution

_No response_

### etc.

_No response_

### LINKED ISSUE #1325: [Feature]: Deprecate QueryErrorBoundary?
### Package Scope

@suspensive/react-query

### Description

```text
// optional-peer-dep:__vite-optional-peer-dep:@suspensive/react:@suspensive/react-query-4
throw new Error(`Could not resolve "@suspensive/react" imported by "@suspensive/react-query-4". Is it installed?`);
```

Due to the peerDep issue of @suspensive/react-query, some projects have the problem of having to install @suspensive/react. The implementation of QueryErrorBoundary is simple and leaving this implementation up to the user seems to end these problems and solve the peerDep problem.

@gwansikk I want to talk about this issue

### Possible Solution

_No response_

### etc.

_No response_

### LINKED ISSUE #1349: [Bug]: peerDependency error of @suspensive/react when using @suspensive/react-query standalone
### Package Scope

@suspensive/react, @suspensive/react-query, @suspensive/react-query-4, @suspensive/react-query-5

### Bug description

When using `@suspensive/react-query` as standalone, I'm getting a peerDependency error for `@suspensive/react`. 

```
Failed to compile.

../../node_modules/.pnpm/@suspensive+react-query-5@2.18.4_@tanstack+react-query@5.59.16_react@18.3.1/node_modules/@suspensive/react-query-5/dist/chunk-AT3YTYWU.js
Module not found: Can't resolve '@suspensive/react'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../node_modules/.pnpm/@suspensive+react-query-5@2.18.4_@tanstack+react-query@5.59.16_react@18.3.1/node_modules/@suspensive/react-query-5/dist/index.js
../../node_modules/.pnpm/@suspensive+react-query@2.18.4_@tanstack+react-query@5.59.16_react@18.3.1/node_modules/@suspensive/react-query/dist/index.js
./app/clubs/[id]/page.tsx
```

- Node.js: 20.10.0
- Next.js: 14
- @tanstack/react-query: 5
- @suspensive/react-query: 2.18.4

### Expected behavior

According to the official documentation, we should only need to install:

```cmd
npm install @suspensive/react-query @tanstack/react-query
```

### To Reproduce

https://codesandbox.io/p/sandbox/optimistic-wood-c4jp33

image

### Possible Solution

_No response_

### etc.

Is this intended behavior? It seems we might need to address this gap in one of two ways:

1. Documentation could be updated to include `@suspensive/react` installation:
   ```bash
   npm install @suspensive/react-query @suspensive/react @tanstack/react-query

2. Or the peerDependency configuration could be adjusted to align with the current documentation

### PR DESCRIPTION
**Pull request by manudeli**
close #1108 close #1349 close #1325

# Suspensive v3

Check https://v3.suspensive.org

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/toss/suspensive/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

**Comment by manudeli** [comment]
Thanks for reporting important issues (#1325, #1325, #1349, #1409)! We've fixed them, and now you can try the prerelease version. 🚀

@pocojang @LineGu @lucas0530 Your feedback has been really helpful, so I co-authored you guys too in v3. and we'd love to hear any thoughts on the updates! Let us know if you run into anything. 

### Before (AS-IS)
```json
{
  "dependencies": {
    "@suspensive/react": "^2.18.4",
    "@suspensive/react-query": "npm:@suspensive/react-query-4@^2.18.4"
  }
}
```

### After (TO-BE)
```json
{
  "dependencies": {
    "@suspensive/react": "^3.0.0-next.1",
    "@suspensive/react-query": "^3.0.0-next.1"
  }
}
```

We appreciate your support and look forward to your feedback! 😊

File: packages/react/src/ErrorBoundary.tsx [hunk 1]
```diff
@@ -147,22 +127,36 @@ class BaseErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState
...
+          {typeof Fallback === 'function' ? <Fallback error={error} reset={this.reset} /> : Fallback}
+        </FallbackBoundary>
+      )
     }
 
     return (
-      <ErrorBoundaryContext.Provider value={{ ...this.state, reset: this.reset }}>
-        {childrenOrFallback}
-      </ErrorBoundaryContext.Provider>
+      <ErrorBoundaryContext value={{ ...this.state, reset: this.reset }}>{childrenOrFallback}</ErrorBoundaryContext>
```
Comment (manudeli) [inline packages/react/src/ErrorBoundary.tsx:139]:
```suggestion
      <ErrorBoundaryContext.Provider value={{ ...this.state, reset: this.reset }}>{childrenOrFallback}</ErrorBoundaryContext.Provider>
```

Comment (manudeli) [reply packages/react/src/ErrorBoundary.tsx]: This is resolved in @suspensive/react@3.0.0-next.2 👍

**Review by gwansikk — APPROVED** [review]
Let's go go!

**Comment by kangju2000** [comment]
🚀🚀🚀🚀🚀🚀

**Review by kangju2000 — APPROVED** [review]
🚀🚀🚀🚀🚀🚀
